version: "3.7"
services:
  app:
    build:
      args:
        user: lizwi
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: bookings
    container_name: bookings-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - bookings

  db:
    image: mysql:8.0
    container_name: bookings-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - bookings

  nginx:
    image: nginx:alpine
    container_name: bookings-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - bookings

networks:
  bookings:
    driver: bridge